version: 2.1  # Versi칩n de la configuraci칩n de CircleCI

jobs:
  build:
    docker:
      - image: circleci/bash:latest  # Imagen de Docker con Bash
    steps:
      - checkout  # Clona el repositorio
      - run:
          name: Compilar el script de c치lculo
          command: |
            chmod +x calculator.sh  # Hacer el script ejecutable
            echo "Script de c치lculo listo para ejecutar."

  test:
    docker:
      - image: circleci/bash:latest  # Imagen de Docker con Bash
    steps:
      - checkout  # Clona el repositorio
      - run:
          name: Instalar BATS
          command: |
            sudo apt-get update
            sudo apt-get install -y bats  # Instala el framework BATS
      - run:
          name: Ejecutar pruebas unitarias
          command: bats test_calculator.bats  # Ejecuta el archivo de pruebas

workflows:
  version: 2
  build_and_test:
    jobs:
      - build  # Ejecuta el job de Build
      - test:  # Ejecuta el job de Test
          requires:
            - build  # El job de Test depende del job de Build

