version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Cambia a la imagen python deseada
    steps:
      - checkout
      - run:
          name: Compilar Script
          command: |
            echo "#!/bin/bash" > script.sh
            echo "echo 'Hello, CircleCI!'" >> script.sh
            chmod +x script.sh

  test:
    docker:
      - image: circleci/python:3.8  # Cambia a la imagen python deseada
    steps:
      - checkout
      - run:
          name: Ejecutar Pruebas
          command: |
            echo "#!/bin/bash" > test_script.sh
            echo "if ./script.sh; then" >> test_script.sh
            echo "  echo 'Test Passed'" >> test_script.sh
            echo "else" >> test_script.sh
            echo "  echo 'Test Failed'" >> test_script.sh
            echo "fi"
            chmod +x test_script.sh
            ./test_script.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
