name: Syntax Check

on:
  pull_request:
    branches:
      - develop

jobs:
  check-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify README syntax
        run: markdownlint README.md

